@startuml
package "Сервис рекомендаций" {
  [RecommendationController] as RC
  [RuleController] as RLC
  [RuleStatsController] as RSC
  [ManagementController] as MC
  [TelegramBotService] as TBS
  [RecommendationService] as RS
  [KnowledgeBaseService] as KBS
}

database "БД транзакций" as TransactionDB
database "БД правил" as RulesDB
node "Telegram API" as TelegramAPI

RC --> RS : использует
RLC --> RulesDB : читает/пишет
RSC --> RulesDB : читает
MC --> RS : сбрасывает кэш
TBS --> RS : использует
RS --> KBS : использует
RS --> TransactionDB : читает
RS --> RulesDB : читает
KBS --> TransactionDB : читает
TBS --> TelegramAPI : взаимодействует
@enduml